//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3PA.Html {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_3PA.Html.HtmlResources", typeof(HtmlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;AlternatBackColor&quot; style=&quot;margin: 10px 20px; padding: 10px;&quot;&gt;
        ///    &lt;b class=&quot;SubTextColor&quot; style=&quot;font-size: 16px;&quot;&gt;This is an alpha version of the software&lt;/b&gt;&lt;br&gt;&lt;br&gt;
        ///    As such, the software and all its content are provided on an &lt;i&gt;&quot; as is &quot;&lt;/i&gt; and &lt;i&gt;&quot; as available &quot;&lt;/i&gt; basis. I do not give any warranties, whether express or implied, as to the suitability or usability of this software.&lt;br&gt;&lt;br&gt;
        ///    Should you encounter any bugs, glitches, lack of functionality or other problems on the s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string disclaimer {
            get {
                return ResourceManager.GetString("disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;margin: 0px; width: 100%;&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td rowspan=&quot;2&quot; style=&quot;width: 200px&quot;&gt;&lt;img src=&quot;logo200x200&quot; width=&quot;150&quot; height=&quot;150&quot;/&gt;&lt;/td&gt;
        ///        &lt;td style=&quot;font-weight: bold; font-size: 35px;&quot;&gt;&lt;span class=&quot;AccentColor&quot;&gt;P&lt;/span&gt;rogress &lt;span class=&quot;AccentColor&quot;&gt;P&lt;/span&gt;rogrammers &lt;span class=&quot;AccentColor&quot;&gt;P&lt;/span&gt;al &lt;span style=&quot;font-size: 20px;&quot; class=&quot;SubTextColor&quot;&gt;%version%&lt;/span&gt;&lt;a href=&quot;&quot;&gt;&lt;img src=&quot;Update26x26&quot; style=&quot;margin-left: 10px;&quot; title=&quot;Click to check for updates&quot; /&gt;&lt;/a&gt;&lt;/td&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
    }
}
