//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3PA.Html {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_3PA.Html.HtmlResources", typeof(HtmlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;div class=&quot;AlternatBackColor&quot; style=&quot;margin: 10px 20px; padding: 10px;&quot;&gt;
        ///    &lt;b class=&quot;SubTextColor&quot; style=&quot;font-size: 16px;&quot;&gt;This is an alpha version of the software&lt;/b&gt;&lt;br&gt;&lt;br&gt;
        ///    As such, the software and all its content are provided on an &lt;i&gt;&quot; as is &quot;&lt;/i&gt; and &lt;i&gt;&quot; as available &quot;&lt;/i&gt; basis. I do not give any warranties, whether express or implied, as to the suitability or usability of this software.&lt;br&gt;&lt;br&gt;
        ///    Should you encounter any bugs, glitches, lack of functionality or other problems on the s [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string disclaimer {
            get {
                return ResourceManager.GetString("disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # Getting started #
        ///
        ///**I&apos;ll keep this short.** The full documentation can be found [here](http://jcaillon.github.io/3P/).
        ///
        ///***
        ///
        ///## Main menu ##
        ///
        ///Everything starts with 3P&apos;s main menu :
        ///
        ///![image](getting-started-0.png)
        ///
        ///All 3P&apos;s features are accessible from this menu, this is the main entry point. Once you are familiar with the software, you can use the direct shortcuts.
        ///
        ///***
        ///
        ///## Setting an environment ##
        ///
        ///3P has a lot of features that are available immediately, like the auto-completion or  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string getting_started {
            get {
                return ResourceManager.GetString("getting_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;table style=&quot;margin: 0px; width: 100%;&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td rowspan=&quot;2&quot; style=&quot;width: 200px&quot;&gt;&lt;img src=&quot;logo200x200&quot; width=&quot;150&quot; height=&quot;150&quot;/&gt;&lt;/td&gt;
        ///        &lt;td style=&quot;font-weight: bold; font-size: 35px;&quot;&gt;&lt;span class=&quot;AccentColor&quot;&gt;P&lt;/span&gt;rogress &lt;span class=&quot;AccentColor&quot;&gt;P&lt;/span&gt;rogrammers &lt;span class=&quot;AccentColor&quot;&gt;P&lt;/span&gt;al &lt;span style=&quot;font-size: 20px;&quot; class=&quot;SubTextColor&quot;&gt;%version%&lt;/span&gt;&lt;a href=&quot;update&quot;&gt;&lt;img src=&quot;Update26x26&quot; style=&quot;margin-left: 10px;&quot; title=&quot;Click to check for updates&quot; /&gt;&lt;/a&gt;&lt;/ [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
    }
}
