name: Feature Request
description: Suggest an idea to improve 3P
title: "[Feature]: "
labels: [Enhancement]
assignees: "jcaillon"
body:
  - type: markdown
    attributes:
      value: |
       Please fill out the following fields with as much detail as possible:
       Fields marked with an asterisk (*) are required, and remaining fields are optional, but we encourage their usage.
  - type: textarea
    id: feature
    attributes:
      label: Describe feature or enhancement.
      description: A clear and concise description of the feature or enhancement you'd like to see in 3P.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem. Ex. I'm always frustrated when.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: Is it OS specific?
      placeholder: e.g. Windows, MacOS, Linux, Any
    validations:
      required: true
  - type: textarea
    id: Snapshots
    attributes:
      label: Additional context, snapshots, or images
      description: "Add any other context or screenshots about the feature request.\n
      Add attach images which can help explain the feature, and a description of what to look for in the image(s)."
    validations:
      required: false      
