//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3PA._Resource {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_3PA._Resource.DataResources", typeof(DataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] Abbreviations {
            get {
                object obj = ResourceManager.GetObject("Abbreviations", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ApplicationThemes {
            get {
                object obj = ResourceManager.GetObject("ApplicationThemes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] DataDigger {
            get {
                object obj = ResourceManager.GetObject("DataDigger", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] DeploymentHook {
            get {
                object obj = ResourceManager.GetObject("DeploymentHook", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] DeploymentRules {
            get {
                object obj = ResourceManager.GetObject("DeploymentRules", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] DumpDatabase {
            get {
                object obj = ResourceManager.GetObject("DumpDatabase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] DumpTableCrc {
            get {
                object obj = ResourceManager.GetObject("DumpTableCrc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] FunctionImplementation {
            get {
                object obj = ResourceManager.GetObject("FunctionImplementation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] InternalProcedure {
            get {
                object obj = ResourceManager.GetObject("InternalProcedure", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] KeywordsHelp {
            get {
                object obj = ResourceManager.GetObject("KeywordsHelp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] KeywordsList {
            get {
                object obj = ResourceManager.GetObject("KeywordsList", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ProgressRun {
            get {
                object obj = ResourceManager.GetObject("ProgressRun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] Snippets {
            get {
                object obj = ResourceManager.GetObject("Snippets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] StartProlint {
            get {
                object obj = ResourceManager.GetObject("StartProlint", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] SyntaxThemes {
            get {
                object obj = ResourceManager.GetObject("SyntaxThemes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à   &lt;UserLang name=&quot;OpenEdgeABL&quot; ext=&quot;p i t w cls dbg d df&quot; udlVersion=&quot;2.1&quot;&gt;
        ///    &lt;Settings&gt;
        ///      &lt;Global caseIgnored=&quot;yes&quot; allowFoldOfComments=&quot;no&quot; foldCompact=&quot;no&quot; forcePureLC=&quot;0&quot; decimalSeparator=&quot;0&quot; /&gt;
        ///      &lt;Prefix Keywords1=&quot;no&quot; Keywords2=&quot;no&quot; Keywords3=&quot;no&quot; Keywords4=&quot;no&quot; Keywords5=&quot;no&quot; Keywords6=&quot;yes&quot; Keywords7=&quot;no&quot; Keywords8=&quot;no&quot; /&gt;
        ///    &lt;/Settings&gt;
        ///    &lt;KeywordLists&gt;
        ///      &lt;Keywords name=&quot;Comments&quot;&gt;00&amp;amp;ANALYZE-SUSPEND 00&amp;amp;GLOBAL-DEFINE 00&amp;amp;SCOPED-DEFINE 00&amp;amp;SCOPED 00&amp;amp;GLOB 00&amp;am [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string UDL {
            get {
                return ResourceManager.GetString("UDL", resourceCulture);
            }
        }
    }
}
