//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3PA._Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_3PA._Resource.HtmlResources", typeof(HtmlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;AlternatBackColor&quot; style=&quot;margin: 10px 20px; padding: 10px; margin-top: 25px;&quot;&gt;
        ///    &lt;b class=&quot;SubTextColor&quot; style=&quot;font-size: 16px;&quot;&gt;This is a beta version of the software&lt;/b&gt;&lt;br&gt;&lt;br&gt;
        ///    As such, the software and all its content are provided on an &lt;i&gt;&quot; as is &quot;&lt;/i&gt; and &lt;i&gt;&quot; as available &quot;&lt;/i&gt; basis. I do not give any warranties, whether expressed or implied, as to the suitability or usability of this software.&lt;br&gt;&lt;br&gt;
        ///    Should you encounter any bugs, glitches, lack of functionality or other [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string disclaimer {
            get {
                return ResourceManager.GetString("disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Getting started #
        ///
        ///**I&apos;ll keep this short.** A more detailed documentation can be found [here](http://jcaillon.github.io/3P/).
        ///
        ///
        ///## Main menu ##
        ///
        ///Everything starts with 3P&apos;s main menu :
        ///
        ///![image](getting_started_0)
        ///
        ///All 3P&apos;s features are accessible from this menu, this is the main entry point. Once you are familiar with the software, you can use the direct shortcuts.
        ///
        ///
        ///
        ///## Setting an environment ##
        ///
        ///3P has a lot of features that are available immediately, like the autocompletion or the s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string getting_started {
            get {
                return ResourceManager.GetString("getting_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1 style=&quot;padding-top: 0; margin-top: 0&quot;&gt;About 3P&lt;/h1&gt;
        ///
        ///&lt;table style=&quot;margin: 0; width: 100%;&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td style=&quot;width: 160px&quot;&gt;
        ///            &lt;img src=&quot;logo150x150&quot; width=&quot;150&quot; height=&quot;150&quot; /&gt;
        ///        &lt;/td&gt;
        ///        &lt;td&gt;
        ///            &lt;div style=&quot;margin-bottom: 5px;&quot;&gt;
        ///                &lt;div style=&quot;font-size: 20px; margin-bottom: 10px;&quot;&gt;&lt;b&gt;&lt;span class=&quot;AccentColor&quot;&gt;P&lt;/span&gt;rogress &lt;span class=&quot;AccentColor&quot;&gt;P&lt;/span&gt;rogrammers &lt;span class=&quot;AccentColor&quot;&gt;P&lt;/span&gt;al&lt;/b&gt; (or &lt;b&gt;3&lt;span class=&quot;AccentCo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* ==================================== */
        ////* GENRAL STUFF */
        ///
        ///html {
        ///    color: @FormFore;
        ///    Font: 12px &quot;Segoe UI&quot;;
        ///}
        ///
        ///hr {
        ///    border: 0;
        ///    height: 1px;
        ///    background: @FormBorder no-repeat scroll center;
        ///    width: 70%;
        ///}
        ///
        ///a:link {
        ///    color: @GenericLinkColor;
        ///    text-decoration: underline;
        ///}
        ///
        ///pre {
        ///    background-color: @FormAltBack;
        ///    Font: 12px &quot;Consolas&quot;;
        ///}
        ///
        ///code {
        ///    background-color: @FormAltBack;
        ///    padding-left: 5px;
        ///    padding-right: 5px;
        ///    Font: 11px &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StyleSheet {
            get {
                return ResourceManager.GetString("StyleSheet", resourceCulture);
            }
        }
    }
}
