//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace _3PA.Data {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class DataResources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("_3PA.Data.DataResources", typeof(DataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abbreviations {
            get {
                object obj = ResourceManager.GetObject("abbreviations", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] keywords {
            get {
                object obj = ResourceManager.GetObject("keywords", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] keywordsHelp {
            get {
                object obj = ResourceManager.GetObject("keywordsHelp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;ProgressEnvironnement&gt;
        ///    &lt;Label&gt;Environnement de dev BOI&lt;/Label&gt;
        ///    &lt;Appli&gt;BOI&lt;/Appli&gt;
        ///    &lt;EnvLetter&gt;A&lt;/EnvLetter&gt;
        ///    &lt;IniPath&gt;o:\appli\boia\boidevv1110.ini&lt;/IniPath&gt;
        ///    &lt;DicoPfPath&gt;
        ///      &lt;PfPath&gt;
        ///        &lt;Key&gt;0&lt;/Key&gt;
        ///        &lt;Value&gt;o:\appli\boia\boidev.pf&lt;/Value&gt;
        ///      &lt;/PfPath&gt;
        ///    &lt;/DicoPfPath&gt;
        ///    &lt;ProPath/&gt;
        ///    &lt;DataBaseConnection/&gt;
        ///    &lt;CmdLineParameters/&gt;
        ///    &lt;BaseLocalPath&gt;D:\Cnaf\boi-a-dev\boi\&lt;/BaseLocalPath&gt;
        ///    &lt;BaseCompilationPath&gt;O:\appli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProgressEnvironnement {
            get {
                return ResourceManager.GetString("ProgressEnvironnement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] snippets {
            get {
                object obj = ResourceManager.GetObject("snippets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;HighlightTheme&gt;
        ///    &lt;Name Value=&quot;Default&quot; /&gt;
        ///    &lt;UniqueId Value=&quot;0&quot; /&gt;
        ///    &lt;BgDefault Value=&quot;#FFFFFF&quot; /&gt;
        ///    &lt;FgDefault Value=&quot;#4D4D4C&quot; /&gt;
        ///    &lt;FgComment Value=&quot;#718C00&quot; /&gt;
        ///    &lt;FgLineComment Value=&quot;#EAB700&quot; /&gt;
        ///    &lt;FgNumbers Value=&quot;#C82829&quot; /&gt;
        ///    &lt;FgKeyword1 Value=&quot;#183E56&quot; /&gt;
        ///    &lt;BgKeyword1 Value=&quot;#BBDAFF&quot; /&gt;
        ///    &lt;FgKeyword2 Value=&quot;#183E56&quot; /&gt;
        ///    &lt;FgKeyword3 Value=&quot;#2F5E9B&quot; /&gt;
        ///    &lt;FgKeyword4 Value=&quot;#2F5E9B&quot; /&gt;
        ///    &lt;FgKeyword5 Value=&quot;#EAB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyntaxHighlighting {
            get {
                return ResourceManager.GetString("SyntaxHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UserLang name=&quot;OpenEdgeABL&quot; ext=&quot;p i t w cls lst&quot; udlVersion=&quot;2.1&quot;&gt;
        ///  &lt;Settings&gt;
        ///    &lt;Global caseIgnored=&quot;yes&quot; allowFoldOfComments=&quot;no&quot; foldCompact=&quot;no&quot; forcePureLC=&quot;0&quot; decimalSeparator=&quot;0&quot; /&gt;
        ///    &lt;Prefix Keywords1=&quot;no&quot; Keywords2=&quot;no&quot; Keywords3=&quot;no&quot; Keywords4=&quot;no&quot; Keywords5=&quot;no&quot; Keywords6=&quot;yes&quot; Keywords7=&quot;no&quot; Keywords8=&quot;no&quot; /&gt;
        ///  &lt;/Settings&gt;
        ///  &lt;KeywordLists&gt;
        ///    &lt;Keywords name=&quot;Comments&quot;&gt;00&amp;amp;ANALYZE-SUSPEND 00&amp;amp;GLOBAL-DEFINE 00&amp;amp;SCOPED-DEFINE 00&amp;amp;SCOPED 00&amp;amp;GLOB 00&amp;amp;GLOBAL 00&amp;amp;MES [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UDL {
            get {
                return ResourceManager.GetString("UDL", resourceCulture);
            }
        }
    }
}
