//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace _3PA.Data {
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class DataResources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("_3PA.Data.DataResources", typeof(DataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] abbreviations {
            get {
                object obj = ResourceManager.GetObject("abbreviations", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] DumpDatabase {
            get {
                object obj = ResourceManager.GetObject("DumpDatabase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] keywords {
            get {
                object obj = ResourceManager.GetObject("keywords", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] keywordsHelp {
            get {
                object obj = ResourceManager.GetObject("keywordsHelp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;ProgressEnvironnement&gt;
        ///    &lt;Label&gt;Environnement de dev BOI&lt;/Label&gt;
        ///    &lt;Appli&gt;BOI&lt;/Appli&gt;
        ///    &lt;EnvLetter&gt;A&lt;/EnvLetter&gt;
        ///    &lt;IniPath&gt;o:\appli\boia\boidevv1110.ini&lt;/IniPath&gt;
        ///    &lt;DicoPfPath&gt;
        ///      &lt;PfPath&gt;
        ///        &lt;Key&gt;0&lt;/Key&gt;
        ///        &lt;Value&gt;o:\appli\boia\boidev.pf&lt;/Value&gt;
        ///      &lt;/PfPath&gt;
        ///    &lt;/DicoPfPath&gt;
        ///    &lt;ProPath/&gt;
        ///    &lt;DataBaseConnection/&gt;
        ///    &lt;CmdLineParameters/&gt;
        ///    &lt;BaseLocalPath&gt;D:\Cnaf\boi-a-dev\boi\&lt;/BaseLocalPath&gt;
        ///    &lt;BaseCompila [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ProgressEnvironnement {
            get {
                return ResourceManager.GetString("ProgressEnvironnement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] ProgressRun {
            get {
                object obj = ResourceManager.GetObject("ProgressRun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] snippets {
            get {
                object obj = ResourceManager.GetObject("snippets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;StyleTheme&gt;
        ///    &lt;Name Value=&quot;Default&quot; /&gt;
        ///    &lt;UniqueId Value=&quot;0&quot; /&gt;
        ///    &lt;BgDefault Value=&quot;#FFFFFF&quot; /&gt;
        ///    &lt;FgDefault Value=&quot;#000000&quot; /&gt;
        ///    &lt;FgComment Value=&quot;#008000&quot; /&gt;
        ///    &lt;FgLineComment Value=&quot;#804000&quot; /&gt;
        ///    &lt;FgNumbers Value=&quot;#FF0000&quot; /&gt;
        ///    &lt;FgKeyword1 Value=&quot;#000080&quot; /&gt;
        ///    &lt;BgKeyword1 Value=&quot;#FCD54B&quot; /&gt;
        ///    &lt;FgKeyword2 Value=&quot;#000080&quot; /&gt;
        ///    &lt;FgKeyword3 Value=&quot;#0075EA&quot; /&gt;
        ///    &lt;FgKeyword4 Value=&quot;#005EBB&quot; /&gt;
        ///    &lt;FgKeyword5 Value=&quot;#804 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string SyntaxHighlighting {
            get {
                return ResourceManager.GetString("SyntaxHighlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à   &lt;UserLang name=&quot;OpenEdgeABL&quot; ext=&quot;p i t w cls lst&quot; udlVersion=&quot;2.1&quot;&gt;
        ///    &lt;Settings&gt;
        ///      &lt;Global caseIgnored=&quot;yes&quot; allowFoldOfComments=&quot;no&quot; foldCompact=&quot;no&quot; forcePureLC=&quot;0&quot; decimalSeparator=&quot;0&quot; /&gt;
        ///      &lt;Prefix Keywords1=&quot;no&quot; Keywords2=&quot;no&quot; Keywords3=&quot;no&quot; Keywords4=&quot;no&quot; Keywords5=&quot;no&quot; Keywords6=&quot;yes&quot; Keywords7=&quot;no&quot; Keywords8=&quot;no&quot; /&gt;
        ///    &lt;/Settings&gt;
        ///    &lt;KeywordLists&gt;
        ///      &lt;Keywords name=&quot;Comments&quot;&gt;00&amp;amp;ANALYZE-SUSPEND 00&amp;amp;GLOBAL-DEFINE 00&amp;amp;SCOPED-DEFINE 00&amp;amp;SCOPED 00&amp;amp;GLOB 00&amp;amp;GLO [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string UDL {
            get {
                return ResourceManager.GetString("UDL", resourceCulture);
            }
        }
    }
}
